version: "3.9"

services:
  django:
    container_name: backend_django
    restart: always
    build:
      context: .
      dockerfile: ./compose/server/Dockerfile
    volumes:
      - ./my_project
    ports:
      - 8000:8000
    expose:
      - 8000

  front:
    container_name: fronted_vue
    restart: always
    build:
      context: .
      dockerfile: ./compose/client/Dockerfile
    volumes:
      - ./shop_vue
    ports:
      - 8080:8080
    expose:
      - 8080